# Build
FROM node:22-slim AS builder
WORKDIR /app
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --ignore-scripts --network-timeout 600000
COPY . .
RUN yarn build


# Production
FROM node:22-slim AS runner
WORKDIR /app
RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*
COPY package.json yarn.lock ./
RUN yarn install --production --frozen-lockfile --ignore-scripts --network-timeout 600000
COPY --from=builder /app/dist ./dist

ENV NODE_ENV=production
EXPOSE 21165

CMD ["/bin/sh", "-c", "while ! nc -z ${MONGO_HOST:-smallvile} 27017; do sleep 1; done; node dist/main"]
